version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - run:
        name: Check the user name
        command: whoami
      - run:
        name: Check the host name
        command: hostname
      - run:
        name: Check the root directory
        command: ls ~

