version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - run:
          name: Check entries in the home directory
          command: ls -l ~
      - run:
          name: Create a directory
          command: mkdir -p circleci-test
      - run:
          name: Create an empty file
          command: touch circleci-test/empty.txt

