version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - run:
          name: Create an empty file
          command: touch empty.txt
      - run:
          name: Confirm how checksum works
          command: echo {{ checksum ~/empty.txt }}

