version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - run:
          name: Check CIRCLE_BRANCH
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Check Node version
          command: node -v
      - run:
          name: Check npm version
          command: npm -v
      - run:
          name: Check files and folders at /opt/circleci
          command: ls -la /opt/circleci
