version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - run:
          name: Check Node and npm versions
          command: |
            node -v
            npm -v
      - run:
          name: Write environment variables into $BASH_ENV
          command: |
            echo 'export NVM_DIR=/opt/circleci/.nvm' >> $BASH_ENV
            echo '[ -s $NVM_DIR/nvm.sh ] && \. $NVM_DIR/nvm.sh' >> $BASH_ENV
      # - run:
      #     name: Check nvm path
      #     command: which nvm
      - run:
          name: Install Node
          command: |
            # \. /opt/circleci/.nvm/nvm.sh
            nvm install v12
            nvm alias default v12
      - run:
          name: Check Node and npm versions
          command: |
            # \. /opt/circleci/.nvm/nvm.sh
            node -v
            npm -v
