version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - run:
          name: Check CIRCLE_BRANCH
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Check content of $BASH_ENV
          command: cat $BASH_ENV
      - run:
          name: Check Node and npm versions
          command: |
            node -v
            npm -v
      - run:
          name: Check files and folders at /opt/circleci
          command: |
            ls -la /opt/circleci
            ls -la /opt/circleci/.nvm
      - run:
          name: Install Node
          command: |
            \. /opt/circleci/.nvm/nvm.sh
            nvm install v12.14.1
            nvm alias default v12.14.1
      - run:
          name: Check Node and npm versions
          command: |
            \. /opt/circleci/.nvm/nvm.sh
            node -v
            npm -v
