version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - run:
          name: Check Node and npm versions
          command: |
            node -v
            npm -v
      - run:
          name: Set step-wide configurations
          command: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Install Node
          command: |
            nvm install v12
            nvm alias default v12
      - run:
          name: Check Node and npm versions
          command: |
            node -v
            npm -v
